# RFC1738 URL
broker: mqtt://everyone:everyone@globalbroker.meteo.fr:8883

# list of topics to subscribe to
subscribe_topics:
    - 'cache/#'
    - 'origin/#'

# whether to verify data
verify_data: true

# whether to validate message against schema
validate_message: false

# storage: filesystem
storage:
    type: fs
    options:
        path: /tmp/foo/bar
