name: Translate and Deploy MkDocs

on:
  push:
    branches:
      - main
jobs:

  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add this line to grant write access
    outputs:
      translated: ${{ steps.check.outputs.translated }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire commit history to get all changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install openai==0.28

      - name: Run translation script
        id: check
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running translation script..."
          python translate_changed_files.py --changed-only
          
          # Check if there are new changes to commit
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --cached --quiet && echo "translated=false" >> $GITHUB_OUTPUT || (
            git commit -m "Auto-translated docs"
            git push
            echo "translated=true" >> $GITHUB_OUTPUT
          )

  deploy:
    needs: setup
    if: needs.setup.outputs.translated == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-static-i18n mkdocs-table-reader-plugin mkdocs-print-site-plugin

      - name: Deploy with MkDocs
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --config-file documentation/mkdocs.yml --force